# Generated by Django 4.0.4 on 2022-04-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_bake_app', '0003_alter_berry_name_alter_cakeform_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название компании')),
                ('key_word', models.CharField(max_length=256, verbose_name='Ключевое слово')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Рекламная компания',
                'verbose_name_plural': 'Рекламные компании',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TotalAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сумма всех заказов',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='cakes',
        ),
        migrations.AddField(
            model_name='order',
            name='cake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cake_bake_app.cake', verbose_name='Торт'),
        ),
        migrations.DeleteModel(
            name='OrderCake',
        ),
        migrations.AddField(
            model_name='order',
            name='advertising_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertising_company', to='cake_bake_app.advertisingcompany', verbose_name='Рекламная компания'),
        ),
    ]
