# Generated by Django 4.0.4 on 2022-04-29 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_bake_app', '0004_advertisingcompany_totalamount_remove_order_cakes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='title',
            field=models.CharField(blank=True, max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cake_bake_app.cake', verbose_name='Торт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
