# Generated by Django 4.0.4 on 2022-05-01 07:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cake_bake_app', '0008_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualOrderProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Необработанные заказы',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cake_bake_app.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
