# Generated by Django 4.0.4 on 2022-05-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_bake_app', '0009_actualorderproxy_order_email_order_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
