# Generated by Django 4.0.4 on 2022-05-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_bake_app', '0011_alter_totalamount_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='order',
            name='advertising_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cake_bake_app.advertisingcompany', verbose_name='Рекламная компания'),
        ),
    ]
